### ISSUE TITLE
Library dependencies

### ISSUE THREAD

**Issue by Zileus** [kevinpt/symbolator#5]
Hi Kevinpt,

I installed symbolator on a Debian VM (latest version) with the  "pip" command. Everything has been installed but I could not generate the SVG file.. This is surely the dependecy. 

Could you be more precise on which library or packages, I should have installed on my OS?

Regards

**Comment by kevinpt** [comment]
Symbolator only processes component definitions. You must copy the entity into a package as a component and it will be parsed:

> package reset_generator_pkg is
>   component reset_generator is
>     generic(
>       RESET_ACTIVE_LEVEL : std_logic := '1'; --# Asynchronous reset level
>       PERIOD : time := 20 ns;                --# Reset time
>       LENGTH : natural := 1                  --# Reset hold length
>     );
>     port(
>       rst : out std_logic  --# Reset signal
>     );
>   end component reset_generator;
> end package;
